# syntax=docker/dockerfile:1
FROM ruby:2.5

RUN apt-get update -qq && apt-get install -y nodejs postgresql-client cron rsyslog

WORKDIR /myapp

COPY Gemfile /myapp/Gemfile
COPY Gemfile.lock /myapp/Gemfile.lock

RUN bundle install

COPY cron_daily/archive_cron /etc/cron.d/test-cron

RUN chmod 0644 /etc/cron.d/test-cron
RUN chown root /etc/cron.d/test-cron
RUN crontab /etc/cron.d/test-cron
RUN touch /var/log/cron.log


CMD cron && tail -f /var/log/cron.log
